### ISSUE TITLE
Clean up our approach to config

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#2785] opened 2018-10-11 16:08 UTC

**Comment by kenoir** [comment] 2018-11-06 11:55
Closing as dupe of https://github.com/wellcometrust/platform/issues/2964 & https://github.com/wellcometrust/platform/issues/2968

**Comment by alexwlchan** [comment] 2018-11-07 09:48
Re-opening and re-scoping to cover the config cleanups.

**Comment by alexwlchan** [comment] 2018-11-07 11:21
Ah, it’s actually a dupe of #2967.

**Closed by alexwlchan** 2018-11-07 11:21 UTC
