### ISSUE TITLE
Archivematica is failing to create a SIP from appraisal

### ISSUE THREAD

**Issue by aray-wellcome** [wellcometrust/platform#4021] opened 2019-11-04 11:58 UTC
Expected behavior: When pressing Create SIP for appraised items, the SIP should be created and appear on the Ingest tab

Actual behavior: When trying to create a SIP from the appraisal tab, the SIP cannot be created. It fails with the following error messages: 

SIP could not be started! Check dashboard logs.
Failed to copy files to SIP arrange; check Dashboard logs.

**Comment by helenst** [comment] 2019-11-28 13:41
I am having problems getting a transfer into the backlog in the first place - not sure whether this was always a problem but seems to be related to https://github.com/archivematica/Issues/issues/744 for which there is a fix - I'm going to try cherry picking this.

**Comment by helenst** [comment] 2019-11-28 14:07
@aray-wellcome Once I've got something to use in the backlog, what are the steps I need to follow to reproduce this? (I'm not so familiar with this bit of Archivematica :)

**Comment by aray-wellcome** [comment] 2019-11-28 14:21
@helenst It's been a while but here's what I think I did so you can try to replicate:
1. On the Appraisal tab, click Search Transfer Backlog
2. All items in the backlog should appear in the backlog section on the left-hand side of the screen
3. Expand a transfer folder
4. Select multiple files
5. Enter a name in the tag box 
5. Click Add tag to selected files
6. On right hand side of screen under Arrangement, select tag from drop down and click Create SIP

Expected behavior is that the SIP would be created and process would move to the ingest page. But instead, at that point I would get a notice about the SIP not being created. 

I've also tried the same as above but without tags and I believe I did it this way:
1. On the Appraisal tab, click Search Transfer Backlog
2. All items in the backlog should appear in the backlog section on the left-hand side of the screen
3. Expand a transfer folder
4. Click Add Directory on Arrangement and name it
5. Drag and drop a number of files (can only be dragged one at a time) into the directory
6. Click Create SIP

**Comment by helenst** [comment] 2019-11-28 14:27
Hmm, that's odd - it is working on my local setup. Maybe something got fixed in the meantime... once staging's back up, let's check it again :)

**Comment by alexwlchan** [comment] 2019-12-02 07:38
@helenst Staging is back up, so we should be able to investigate this issue again.

But right now I don't see anything when I click "Search Transfer Backlog" – the Elasticsearch indexes are empty. I'm going to try setting the SEARCH_ENABLED environment variables and running another transfer through, see if that makes a difference.

**Comment by alexwlchan** [comment] 2019-12-02 08:35
That didn't seem to make a difference. :(

**Comment by helenst** [comment] 2019-12-03 16:39
I've added a fix for transfers going into the backlog (but it also has to be enabled / selected as part of the workflow, or nothing will go in there). There are a couple of things in there now.

I am seeing this error though:

```
ERROR     2019-12-03 16:32:59  django.request:base:handle_uncaught_exception:256:  Internal Server Error: /filesystem/copy_from_arrange/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/src/dashboard/src/components/filesystem_ajax/views.py", line 481, in copy_from_arrange_to_completed
    filepath, sip_uuid, sip_name
  File "/src/dashboard/src/components/filesystem_ajax/views.py", line 578, in _copy_from_arrange_to_completed_common
    error = _create_arranged_sip(staging_sip_path, files, sip_uuid)
  File "/src/dashboard/src/components/filesystem_ajax/views.py", line 444, in _create_arranged_sip
    os.mkdir(os.path.join(staging_abs_path, directory))
OSError: [Errno 2] No such file or directory: '/var/archivematica/sharedDirectory/staging/ppthw/logs'
```

which could well be related to the original problem here.

**Comment by helenst** [comment] 2019-12-04 14:12
Turned out to be the sharedDirectory mount being not present. This does appear to work on staging now...

@aray-wellcome when you get a chance please could you confirm that it's OK on staging now? If it's not, let me know and we can take another look tomorrow or Friday when I'm in :)

**Comment by aray-wellcome** [comment] 2019-12-05 17:01
@helenst Set a SIP creation from the backlog off last night and just checked on it after my workshop. It _did_ move the item to the Ingest page but it's not letting me create a SIP and move it along. I'm stuck in a loop of approving SIP creation and it failing on Attempt restructure for compliance. I'm not sure if it's something I did or what when creating the SIP or if it's just not working no matter what. We can look at it tomorrow together if you want!

![image](https://user-images.githubusercontent.com/49983203/70256745-eb59b900-1780-11ea-808b-99a4d3a3a57d.png)

**Comment by helenst** [comment] 2019-12-06 11:38
Hmm, yes I am getting this locally too. Worth noting that this happens before any Wellcome storage related stuff happens, so it may well be a core Archivematica issue. I can't immediately find anything in Archivematica issues - but I'm going to test with plain AM / latest builds to see if it happens there.

**Comment by helenst** [comment] 2019-12-11 16:19
Having tested with latest Archivematica QA, this still happens. I have no further insights as to why, but will raise the issue on the core repo. Before tackling this, it would probably be best to bring the latest changes from Artefactual QA into our own repositories.

**Comment by helenst** [comment] 2019-12-12 12:06
https://github.com/archivematica/Issues/issues/1031

**Comment by helenst** [comment] 2020-01-03 18:37
Created pull request in core AM: 
https://github.com/artefactual/archivematica/pull/1534

Should be straightforward to pull into our branch. I'll do this tomorrow.

**Closed** 2020-01-08 09:53 UTC
Labels: 🤖 Archivematica
