### ISSUE TITLE
Outstanding DDS migration issues

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#3957] opened 2019-10-23 13:24 UTC
These are some outstanding issues identified by Ashley with items migrated to DDS:

**Need resolving:**

Migrated (Maybe bagger/DDS):
- [x] Audio will not play, e.g. b29524362_0001, b17307703, b29524350_0001, b31630157 - Update: all audio working except for b17307922 due to a poster image issue that Tom Crane needs to look at - Digirati. Poster image is at https://wellcomelibrary.org/posterimages/b17307922/0056-0000-4402-0102-0-0000-0000-0.jpg
- [x] b17307922 (https://wellcomelibrary.org/item/b17307922) doesn't play
- [x] Chemist & Druggist: No manifest present on havana:88. On UAT site the UV will try to show the first volume before freezing and crashing the tab in my browser
- [x] b17729555 isn't displaying on the library website, possibly because the filenames in storage don't have a b17729555_ prefix - Digirati

New (Maybe Goobi/DDS):
- [x] b19207256, b18518801: have images with the error unknown error during post-tizer operations.
- [x] Video issue on b30698327: `[FileNotFoundException: File not present in storage map: file:///opt/digiverso/viewer/media/b30698327/b30698327.JP2]`

We need to ensure these issues have been addressed and resolved.

**Comment by aray-wellcome** [comment] 2019-10-31 10:05
@alexwlchan I was looking around at b17729555 and some other archives stuff. I think I was wrong about the pre-fix because b11916576 has a file without the bnumber pre-fix and is working just fine in DDS and on live UV. However, b17729555 does have filenames with a space in them instead of an underscore...so maybe it's that.

**Comment by alexwlchan** [comment] 2019-11-07 10:59
I’m going to punt b17729555 back to Digirati.

The IIIF manifest refers to an identifier `b17729555_PP_AEM_K 179_0001.jp2`. https://wellcomelibrary.org/iiif/b17729555/manifest

If you query https://api.dlcs.io/customers/2/spaces/5/images/b17729555_PP_AEM_K%20179_0001.jp2, you see that it knows where to find that image:

```json
  "origin": "https://s3-eu-west-1.amazonaws.com/wellcomecollection-storage/digitised/b17729555/v1/data/objects/PP_AEM_K 179_0001.jp2",
```

(Notice this key correctly omits a b17729555_ prefix.)

**Comment by tomcrane** [comment] 2019-11-12 18:54
> b17729555 isn't displaying on the library website

I think was fixed by @fractos applying the space in identifier support the images pathway on 7 Nov.
It's working for me on the site - the only place it doesn't work is when you hover over the thumbnail image in the dashboard view - that should present a larger thumbnail, but it doesn't, it appears broken. This is using a bootstrap tooltip component that is getting confused by the missing space.

I'll see if I can fix that.

**Comment by tomcrane** [comment] 2019-11-12 19:12
OK, thumbnail dashboard issue fixed for b17729555

**Comment by tomcrane** [comment] 2019-11-12 19:27
b17307922 - this isn't a poster image issue at all - I was getting confused by earlier mentions of JP2s in the bag.

Its poster image is working just fine - here it is:

https://wellcomelibrary.org/posterimages/b17307922/0056-0000-4402-0102-0-0000-0000-0.jpg

This uses the new model - but this is an old, migrated example. The problem is that the MP3 in storage isn't an MP3 - it's that book cover. I thought all those had been re-bagged, but maybe this one was missed because it's not an image (not _supposed_ to be an image). So there was a JP2 in the bag, even if it was trying to pass itself off as an MP3.

**Comment by alexwlchan** [comment] 2019-11-13 12:41
Florence is chatting again, so we're done! 🎉

**Closed by alexwlchan** 2019-11-13 12:41 UTC
Labels: 📦 Storage service
