### ISSUE TITLE
Reliably complete 1% bagging without error

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3297] opened 2019-01-17 15:56 UTC
Triage:

Bagging Errors
--
### 2019-03-05

*Expecting one DeliverableUnit*

- b2103364x | 2019-03-05 01:10:23+00:00 KeyError: 'Expecting one DeliverableUnit XML block; saw 0'

*Unable to find source*

- b2064274x | 2019-03-05 02:00:31+00:00 RuntimeError: Unable to find source for b2064274x: mets/x/4/7/2/b2064274x_alto/epb_msl_tracts_mst_259_13_0001.xml

*Expected 1 AMD ref for AMD_???, got 0*

- b1772515x | 2019-03-05 20:08:38+00:00 RuntimeError: Expected 1 AMD ref for AMD_0082, got 0, filename: PP_AEM_A_212_0080.jp2

### 2019-03-04

*Expected 1 AMD ref for AMD_???, got 0*

- b2047104x | 2019-03-04 18:09:54+00:00 RuntimeError: Unable to find source for b2047104x: mets/x/4/0/1/b2047104x_alto/epb_p_12795_p_0001.xml

### 2019-03-02

*Expected 1 AMD ref for AMD_???, got 0*

- b1000371x | 2019-03-02 01:58:37+00:00 RuntimeError: Expected 1 AMD ref for AMD_1029, got 0, filename: b1000371x_hin-wel-all-00000305_1028.jp2
- b2156081x | 2019-03-02 01:57:17+00:00 RuntimeError: Expected 1 AMD ref for AMD_0282, got 0, filename: sa_con_c_2_0281.JP2
- b1816481x | 2019-03-02 03:10:32+00:00 RuntimeError: Expected 1 AMD ref for AMD_0075, got 0, filename: PP_CRI_C_1_4_0074.jp2
- b1773471x | 2019-03-02 02:03:45+00:00 RuntimeError: Expected 1 AMD ref for AMD_0011, got 0, filename: pp_aem_a_117_box_5_b1773471x_1335331597589.xml

### 2019-02-28

*Expected 1 AMD ref for AMD_???, got 0*

- b1032687x | 2019-02-28 03:14:27+00:00 RuntimeError: Expected 1 AMD ref for AMD_0394, got 0, filename: b1032687x_hin-wel-all-00000973_0393.jp2
- b1010737x | 2019-02-27 22:35:24+00:00 RuntimeError: Expected 1 AMD ref for AMD_0172, got 0, filename: b1010737x_hin-wel-all-00000198_0171.jp2

### 2019-02-26

*Unable to find source*
- b1978496x | 2019-02-27 03:58:59+00:00 RuntimeError: Unable to find source for b1978496x: mets/x/6/9/4/b1978496x_alto/b1978496x_0027.xml
- b2107446x | 2019-02-26 23:21:21+00:00 RuntimeError: Unable to find source for b2107446x: mets/x/6/4/4/b2107446x_alto/b2107446x_0343.xml

*XML mismatched tag*
- b2236156x | 2019-02-26 22:57:24+00:00 xml.etree.ElementTree.ParseError: mismatched tag: line 374, column 11

*Missing asset*
- b1616006x | 2019-02-26 18:00:06+00:00 AssertionError: Unable to find asset 349bcb90-6b90-4690-882e-d68a35b030b6
- b1665836x | 2019-02-26 22:02:27+00:00 AssertionError: Unable to find asset fbf9ec34-90d2-4c88-a225-c036853236c8

### 2019-02-25

*Expected 1 AMD ref for AMD_???, got 0*

- b1772515x | 2019-02-25 19:43:19+00:00 RuntimeError: Expected 1 AMD ref for AMD_0082, got 0, filename: PP_AEM_A_212_0080.jp2

### 2019-02-22

*Expected 1 AMD ref for AMD_???, got 0*

- b1119912x | 2019-02-22 18:31:07+00:00 RuntimeError: Expected 1 AMD ref for AMD_0098, got 0, filename: b1119912x_hin-wel-all-00001294_0097.jp2
- b1010642x | 2019-02-22 19:14:21+00:00 RuntimeError: Expected 1 AMD ref for AMD_0048, got 0, filename: b1010642x_hin-wel-all-00001685_0047.jp2

*KeyError: File format (bad PRONOM mapping)*

- b3020902x | 2019-02-22 18:06:25+00:00 KeyError: 'Acrobat PDF/X - Portable Document Format - Exchange 1:1999 / Acrobat PDF/X - Portable Document Format - Exchange 1a:2003 / Acrobat PDF/X - Portable Document Format - Exchange 2:2003 / Acrobat PDF/X - Portable Document Format - Exchange 3:2003 / Acrobat PDF/X - Portable Document Format - Exchange 1a:2001 / Acrobat PDF/X - Portable Document Format - Exchange 3:2002 / Acrobat PDF/A - Portable Document Format 2a / Acrobat PDF/A - Portable Document Format 2b / Acrobat PDF/A - Portable Document Format 2u / Acrobat PDF/A - Portable Document Format 3a / Acrobat PDF/A - Portable Document Format 3b / Acrobat PDF/A - Portable Document Format 3u / Acrobat PDF/X - Portable Document Format - Exchange PDF/X-4 / Acrobat PDF/X - Portable Document Format - Exchange PDF/X-4p / Acrobat PDF/X - Portable Document Format - Exchange PDF/X-5g / Acrobat PDF/X - Portable Document Format - Exchange PDF/X-5pg / Acrobat PDF/X - Portable Document Format - Exchange PDF/X-5n / Acrobat PDF/E - Portable Document Format for Engineering PDF/E-1 / Acrobat PDF/A - Portable Document Format 1a'

### 2019-02-21

*AssertionError: Expected 1 AMD ref for AMD_???, got 0*

- b1000371x | 2019-02-21 19:42:55+00:00 AssertionError: Expected 1 AMD ref for AMD_1029, got 0
- b2156081x | 2019-02-21 20:10:01+00:00 AssertionError: Expected 1 AMD ref for AMD_0282, got 0
- b1816481x | 2019-02-21 20:18:19+00:00 AssertionError: Expected 1 AMD ref for AMD_0075, got 0
- b1773471x | 2019-02-21 19:55:54+00:00 AssertionError: Expected 1 AMD ref for AMD_0011, got 0

### 2019-02-20

*Unable to find METS file* - Tom checking

- b2246220x | 2019-02-20 18:38:24+00:00 RuntimeError: Unable to find METS file for b2246220x!

### 2019-02-19

*AssertionError: Expected 1 AMD ref for AMD_???, got 0*

- b1119909x | 2019-02-19 18:14:20+00:00 AssertionError: Expected 1 AMD ref for AMD_0189, got 0
- b1623179x | 2019-02-19 19:34:04+00:00 AssertionError: Expected 1 AMD ref for AMD_0024, got 0
- b1802869x | 2019-02-19 19:53:43+00:00 AssertionError: Expected 1 AMD ref for AMD_0436, got 0

*Unable to find METS file* - Tom checking

- b1803049x | 2019-02-19 19:00:28+00:00 RuntimeError: Unable to find METS file for b1803049x!
- b2047099x | 2019-02-19 20:27:36+00:00 RuntimeError: Unable to find METS file for b2047099x!
- b2107429x | 2019-02-19 18:46:51+00:00 RuntimeError: Unable to find METS file for b2107429x!

*SSL error* - Tom rerunning manually
- b1802239x | 2019-02-19 18:52:06+00:00 requests.exceptions.SSLError: HTTPSConnectionPool(host='wellcomelibrary.org', port=443): Max retries exceeded with url: /service/asset/6cd642c0-04ed-4d26-8aa0-215b727d4742 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:833)'),))
-- | --

### 2019-02-15

*AssertionError: Expected 1 AMD ref for AMD_???, got 0*

- b1773535x | 2019-02-15 18:41:15+00:00 AssertionError: Expected 1 AMD ref for AMD_0094, got 0
- b1772515x | 2019-02-15 18:19:29+00:00 AssertionError: Expected 1 AMD ref for AMD_0082, got 0
- b1010642x | 2019-02-15 11:44:25+00:00 AssertionError: Expected 1 AMD ref for AMD_0048, got 0
- b1119912x | 2019-02-15 10:53:28+00:00 AssertionError: Expected 1 AMD ref for AMD_0098, got 0

*KeyError: File format*

- b2897685x | 2019-02-15 20:14:32+00:00 KeyError: 'Waveform Audio (PCMWAVEFORMAT)'
- b3020902x | 2019-02-15 10:35:19+00:00 KeyError: 'Acrobat PDF/X - Portable Document Format - Exchange 1:1999 / Acrobat PDF/X - Portable Document Format - Exchange 1a:2003 / Acrobat PDF/X - Portable Document Format - Exchange 2:2003 / Acrobat PDF/X - Portable Document Format - Exchange 3:2003 / Acrobat PDF/X - Portable Document Format - Exchange 1a:2001 / Acrobat PDF/X - Portable Document Format - Exchange 3:2002 / Acrobat PDF/A - Portable Document Format 2a / Acrobat PDF/A - Portable Document Format 2b / Acrobat PDF/A - Portable Document Format 2u / Acrobat PDF/A - Portable Document Format 3a / Acrobat PDF/A - Portable Document Format 3b / Acrobat PDF/A - Portable Document Format 3u / Acrobat PDF/X - Portable Document Format - Exchange PDF/X-4 / Acrobat PDF/X - Portable Document Format - Exchange PDF/X-4p / Acrobat PDF/X - Portable Document Format - Exchange PDF/X-5g / Acrobat PDF/X - Portable Document Format - Exchange PDF/X-5pg / Acrobat PDF/X - Portable Document Format - Exchange PDF/X-5n / Acrobat PDF/E - Portable Document Format for Engineering PDF/E-1 / Acrobat PDF/A - Portable Document Format 1a'

This error implies we should add the additional PRONOM mappings to the bagger, @jtweed can you confirm and we'll add these?

Service errors:

*

Production errors:

**KeyError: 'Expecting one DeliverableUnit XML block'**
* [ ]  b2119693x "KeyError: erableUnit XML block'"
  see https://github.com/wellcometrust/platform/issues/2674

**AssertionError: Expected 1 AMD ref for AMD_0194, got 0"**
* [ ] b1802063x "AssertionError: Expected 1 AMD ref for AMD_0194, got 0"
   AMD ref for b1802063x refers to a JP2.

**Comment by alexwlchan** [comment] 2019-02-14 13:42
To record a conversation from Slack: METS with anything but one DeliverableUnit XML block should be flagged as an error for production, not worked around in the bagger.

https://wellcome.slack.com/archives/CBT40CMKQ/p1550151410057100

**Comment by alexwlchan** [comment] 2019-02-18 10:23
I already added one PRONOM mapping here: https://github.com/wellcometrust/storage-service/pull/36

That PDF one is weird, and doesn't seem to correspond to an existing PRONOM key (more a collection of them!).

**Comment by tomcrane** [comment] 2019-02-21 12:24
Notes on above wronguns:

(see also https://github.com/wellcometrust/platform/issues/2674#issuecomment-435367080)

b3020902x is the one that thinks it's every format under the sun. _There can only one._ I think this should be corrected at source via Goobi.

### Unable to find METS file (actually METS-ALTO)
b2246220x -  the ALTO file asserted in the METS is not present on disk: 
`mets/x/0/2/2/b2246220x_alto/b2246220x_0034.xml`. In this case, it's the last image in the book - https://wellcomelibrary.org/item/b2246220x#?c=0&m=0&s=0&cv=31

b1803049x - mets/x/9/4/0/b1803049x_alto/b1803049x_0383.xml. Also not present on disk:
![image](https://user-images.githubusercontent.com/1443575/53164461-21e68e80-35c8-11e9-988f-8c0ece4ae5f4.png)

b2047099x - mets/x/9/9/0/b2047099x_alto/epb_b_11388_b_0001.xml
None of b2047099x's alto files are present on disk. Note the non-conventional file name. I suspect that this is a leftover experiment from running archive content through OCR. As it claims to have ALTO, the DDS provides the search service and the full text, but there's not very much text to search: https://wellcomelibrary.org/service/fulltext/b2047099x/0

b2107429x - mets/x/9/2/4/b2107429x_alto/b2107429x_0477.xml
This one is missing the last 5 of its claimed ALTO files.

### SSL Error

b1802239x - Sierra has no memory of this...
https://search.wellcomelibrary.org/iii/encore/record/C__Rb1802239?lang=eng
However, the bagger has a go at it. For this item (which I very strong suspect is Closed or Restricted), the DDS can't obtain the JP2s from either Preservica's cloud storage adaptor bucket (because it was put into Preservica before the cloud storage came along) or the DLCS's local origin bucket (used for things not in the Preservica bucket). It's not in the DLCS's bucket because the DDS would not have sent a Closed item to the DLCS for asset delivery. 
In this scenario, the bagger goes back to wellcomelibrary.org and fetches the assets via a proxy that the DDS exposes as the origin of the asset (which uses HTTP basic auth over ssl, btw). 
I've just bagged this locally, successfully, via this method.

So... what was the cause of the original error? While the bagger was doing on AWS what I've just done locally, it ran into an SSL issue talking to wellcomelibrary.org. Was that some transient weirdness coming through the Wellcome IT estate, or is it reproducible every time the bagger running on AWS does this? I re-ran the bagger, this time by invoking the "real" live bagger, via the dashboard, and it worked:

http://wt-havana:88/Dash/Migration/b1802239x

(I made sure that this wasn't the bag I made from my own machine just before.. I refreshed the page until the new bag appeared).

And here it is, all OK: http://wt-havana:88/Dash/Migration/b1802239x
Storage Manifest: http://wt-havana:88/Dash/StorageManifest/b1802239x

Conclusion - see if this happens again. The SSL problem may lie between the internet and the wellcomelibrary.org estate, through the Wellcome load balancer.

@pollecuttn @jtweed

**Comment by tomcrane** [comment] 2019-02-21 13:01
Additional - the "Expected 1 AMD ref for AMD_???, got 0" error now logs the filename that the techmd section refers to.

```
RuntimeError: Expected 1 AMD ref for AMD_0189, got 0, filename: b1119909x_hin-wel-all-00000181_0187.jp2
```

In this case, there's technical metadata about a file called b1119909x_hin-wel-all-00000181_0187.jp2 (sounds like we should care about it), but there's no entry for this file in the METS Physical StructMap. We could just ignore it (the DDS does, when generating a IIIF manifest, it's guided by the structmap), but the bagger needs to be a bit more "whoa there" than the DDS.

**Comment by tomcrane** [comment] 2019-02-27 13:31
Long diagnosis of the AMD ref issue today with Harkiran, Christy and Natalie.

b1623179x is a particularly good example. It has 23 assets mentioned in the physical and logical structmaps, but about 213 mentioned in the technical metadata section.

We can go to Preservica and look at some of these, and they are clearly parts of the work that should be migrated to the new storage, photographed at some expense, etc. They aren't `thumbs.db` and `__macosx` bits and pieces that shouldn't be preserved (and that we are explicitly ignoring).

They just aren't listed in the structmap parts of the METS, which is what's driving the migration (and what gives us relative file paths within the bag structure).

This particular bnumber looked OK in the Goobi workflow.
Others that exhibit this issue, often only on the very last file in the structmaps, were stalled in the Goobi workflow (for years).

The bagger throws an error when it encounters this mismatch, regardless of the cause, except for thumbs.db junk files.

@pollecuttn @jtweed

**Comment by tomcrane** [comment] 2019-02-27 13:34
Also worth pointing out that missing files like this can only be retrieved from Preservica, they won't be in the buckets the bagger uses by preference. The bagger can fetch them directly from Preservica via the DDS proxy.

**Closed** 2019-03-06 16:20 UTC
Labels: 📦 Storage service
