### ISSUE TITLE
Get pipeline running again

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform#3818] opened 2019-08-07 15:54 UTC
- [x] Fix the bug in the recorder
- [x] Fix the bug with `javax` dependencies
- [x] Fix the bug with `Config` environment variables
- [ ] Verifying dates and titles come through

**Comment by warrd** [comment] 2019-08-09 13:44
# Report: what broke and how's it been fixed

Just writing a summary of whats happened so far, so we have a record of it :)

## Recorder bug

The pipeline was originally failing on the second step, the recorder.

```
io.circe.DecodingFailure: Attempt to decode value on failed cursor: DownField(alternativeTitles)
```

After some investigation it turned out this error would happen when trying to decode json to our `Work` model when the json was missing the `alternativeTitles` field.

This was initially pretty confusing as the incoming messages from the transformer on AWS SQS had that field. It turned out the reason for this is that was that the `HyrbridStore` would fetch the existing data from S3 and decode it to a `Work` (even when there is no need to read from it, just write), and as the existing data was run with an older version of the model it could not be decoded correctly.

The way to avoid these errors was therefore to build a new pipeline from scratch. However, there are some further actions we should take:

- [ ] Document this behaviour to avoid a similar situation with anyone else coming to the codebase
- [ ] Upgrade from `v.3.6.0` to the latest `scala-storage`, which removes the the offending behaviour with the `HybridStore` 
- [ ] Make sure the full stack trace is sent to the logs, as it would be much quicker to diagnose if we knew exactly where the error was being thrown

## `javax` dependency bug

After deploying a new pipeline from scratch the recorder started crashing for another reason:

```
13:49:12.618 [main] INFO u.a.wellcome.platform.recorder.Main$ - Starting worker.

Uncaught error from thread [main-actor-system-akka.actor.default-dispatcher-5]: javax/xml/bind/JAXBException, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[main-actor-system]
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1748)

13:49:54.015 [main] ERROR u.a.wellcome.platform.recorder.Main$ - Fatal error:

akka.stream.AbruptStageTerminationException: GraphStage [akka.stream.impl.fusing.GraphStages$IgnoreSink$$anon$9@5d08db91] terminated abruptly, caused by for example materializer or actor system termination.

13:49:54.017 [main] INFO u.a.wellcome.platform.recorder.Main$ - Terminating worker.
```

This was due to this issue: https://github.com/aws/aws-sdk-java/issues/1092

The fix was to add the explicit dependency [here](https://github.com/wellcometrust/catalogue/pull/107)


## Error decoding environment variables from `Config`

After this the recorder was working as intended, but we were getting errors at the end of the pipeline with the ID minter:

```
Exception in thread "main" java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:103)
at uk.ac.wellcome.platform.idminter.config.builders.RDSBuilder$.buildDB(RDSBuilder.scala:10)
```

The fix for this is here: https://github.com/wellcometrust/catalogue/pull/108

This is likely to be a problem elsewhere in the `catalogue`as well as in any other applications extending `WellcomeTypesafeApp`, so this issue has been captured here: https://github.com/wellcometrust/platform/issues/3824

**Closed** 2019-08-12 10:11 UTC
