### ISSUE TITLE
Item Request Service Authentication

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3916] opened 2019-10-07 14:49 UTC
In order to provide continuity of service an existing library user can sign in to use the Item Request Service.

There are outstanding questions as to whether this should be a user migration or integrate with existing authentication mechanisms.

**Comment by kenoir** [comment] 2019-10-30 09:39
Dupe of https://github.com/wellcomecollection/item-requests-service/issues/7

**Closed by kenoir** 2019-10-30 09:39 UTC
Labels: :tickets: Requests
